---
- name: Deploy Cloud Binary Artifact Unto EC2
  hosts: 'all'
  become: yes
  tasks:

    - name: Update the Repository 
      apt: update_cache=yes
      ignore_errors: yes

    - name: Install Pip
      apt: name=python3-pip state=latest

    - name: Install Futures 
      pip:
        name: [ "futures" ]
        extra_args: "--user"

    - name: Unzip the artifact i.e. /home/ubuntu/cloudbinary
      unarchive:
        src: /home/ubuntu/cloudbinary
        dest: /home/ubuntu
        remote_src: yes  

    - name: Deploy cloudbinary-5.0.0.war unto DocumentRoot
      copy:
        src: /home/ubuntu/target/cloudbinary-5.0.0.war
        dest: /opt/tomcat/webapps/